version: '3.7'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb:
